name: IOT_BKHCM
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.0.0
  sqflite: ^2.2.8
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_tts: ^4.0.0
  flutter_animate: ^4.5.0 # Thêm cho hiệu ứng động
  fl_chart: ^0.68.0 # Thêm cho biểu đồ
  provider: ^6.1.2 # Thêm cho quản lý trạng thái
  cached_network_image: ^3.3.1 # Thêm cho tải hình ảnh
  intl: ^0.17.0
  uuid: ^4.0.0
  onesignal_flutter: ^5.2.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/app_logo.png
    - assets/images/livingroom.jpg
    - assets/images/bedroom.jpg
    - assets/images/kitchen.jpg
    - assets/images/workingroom.jpg
    - assets/images/fire_alert.png
    - assets/images/access_control.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  android: true
  ios: false
  color: "#ffffff" # Màu nền splash screen
  image: assets/images/app_logo.png # Đường dẫn hình ảnh

  # Tùy chỉnh riêng cho Android 12, 13, 14, 15
  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#ffffff"